#!/bin/bash
# //====================================================
# //	System Request:Debian 9+/Ubuntu 18.04+/20+
# //	Author:	bhoikfostyahya
# //	Dscription: Xray Menu Management
# //	email: admin@bhoikfostyahya.com
# //  telegram: https://t.me/bhoikfost_yahya
# //====================================================
# // font color configuration | BHOIKFOST YAHYA AUTOSCRIPT
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
IP=$(curl -s ipv4.icanhazip.com)
HOST="$(cat /etc/xray/domain)"
DATEVPS=$(date +"%d-%B-%Y")
ISPVPS=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
GREEN="\e[92;1m"
BLUE="\033[36m"
RED='\033[0;31m'
NC='\033[0m'
read -p "Plase Input Link : " DATAVPS
function RESTOREVPS() {
    wget -O backup.zip "$DATAVPS" >/dev/null 2>&1
    unzip *.zip >/dev/null 2>&1
    #    rm -f *.zip >/dev/null 2>&1
    cd /root/backup
    cp passwd /etc/
    cp group /etc/
    cp shadow /etc/
    cp gshadow /etc/
    cp -r kyt /var/lib/
    cp -r xray /etc/
    cp -r vmess /etc/
    cp -r vless /etc/
    cp -r trojan /etc/
    cp -r shadowsocks /etc/
    cp -r /ip/vmess /etc/kyt/limit/vmess/ip/
    cp -r /ip/vless /etc/kyt/limit/vless/ip/
    cp -r /ip/trojan /etc/kyt/limit/trojan/ip/
    cp -r /ip/shadowsocks /etc/kyt/limit/shadowsocks/ip/
    cp -r /ip/ssh /etc/kyt/limit/ssh/ip/
    cp -r html /var/www/
    cp -r cron.d /etc/
    cp crontab /etc/
    cd
    systemctl restart xray >/dev/null 2>&1
    rm -rf backup.zip
    echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━━━◇"
    echo -e "SUCCESSFULL RESTORE YOUR VPS"
    echo -e "Please Save The Following Data"
    echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━━━◇"
    echo -e "Your VPS IP : $IP"
    echo -e "DOMAIN      : $HOST"
    echo -e "DATE        : $DATEVPS"
    echo -e "ISP         : $ISPVPS"
    echo -e "LOCATION    : $CITY"
    echo -e "◇━━━━━━━━━━━━━━━━━━━━━━━━━◇"
    echo -e "Please Reboot Vps"
}
RESTOREVPS
